security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_CUSTOMER: ['ROLE_CUSTOMER']
        ROLE_TECHNICIAN: ['ROLE_TECHNICIAN']
        ROLE_ADMIN: ['ROLE_ADMIN']

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        app_customer_provider:
            entity:
                class: App\Entity\Customer
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_login:
            pattern: ^/api/admin/login
            stateless: true
            json_login:
                check_path: /api/admin/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            provider: app_user_provider

        customer_login:
            pattern: ^/api/customer/login
            stateless: true
            json_login:
                check_path: /api/customer/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            provider: app_customer_provider

        admin:
            pattern: ^/api/admin
            stateless: true
            lazy: true
            entry_point: jwt
            jwt: 
                provider: app_user_provider
            refresh_jwt:
                provider: app_user_provider
        api:
            pattern: ^/api
            stateless: true
            lazy: true
            entry_point: jwt
            jwt: 
                provider: app_customer_provider
            refresh_jwt:
                provider: app_customer_provider


    access_control:
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/customer/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/customer, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/admin/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/admin/customer, roles: ROLE_TECHNICIAN }
        - { path: ^/api/admin/brands, roles: ROLE_TECHNICIAN }
        - { path: ^/api/admin/equipment, roles: ROLE_TECHNICIAN }
        - { path: ^/api/admin/intervention, roles: ROLE_TECHNICIAN }
        - { path: ^/api/admin/company, roles: ROLE_ADMIN }


when@test:
    doctrine:
        dbal:
            dbname_suffix: ''
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10